### ISSUE TITLE
Add -s | --summary flag 

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/artix-news#1]
![image](https://user-images.githubusercontent.com/7642878/52955969-c9678500-336c-11e9-81ba-39e531c5c9b4.png)

It should behaves as like when called: `artix-news -s`. It should uses libraries like `argparse` and `re`. No external dependencies it's allowed.

**Comment by hurani** [comment]
found this through good first issue, submitted PR :)

**Comment by ryukinix** [comment]
Nice :) thanks for the contribution.
